# Generated by Django 4.2.6 on 2023-10-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('psychologist', 'psychologist'), ('psychiatrist', 'psychiatrist')], default='Cardiologist', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
